In [10]:
# fold
import cv2
import glob
import matplotlib.pyplot as plt
import math
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils
from keras import optimizers
# For some reason I have to tell it to use TensorFlows dimension ordering
from keras import backend as K
K.set_image_dim_ordering('tf')

def get_images(path, dataSpecs):
    fileList = glob.glob(path) #'BengaliBMPConvert/*.bmp'   
    num = len(fileList)
    dataSpecs['classLength'].append(len(fileList))
    x = np.array([(cv2.imread(fname)) for fname in fileList])
    return x

def get_labels_one_hot(num_classes, class_id, num_samples):
    x = np.zeros((num_samples, num_classes))
    x[np.arange(num_samples),class_id] = 1
    return x
 
    
    
def main():
    import keras
    print(keras.__version__)
    
    # Get images and labels
    print('Started')
    data = {'img': 0, 'label': 0}
    dataSpecs = {'classLength': []}
    dataSpecs['classLength'] = []
    data['img'] = np.concatenate((
            #get_images('/vol/vssp/mammo2/will/data/simulated/calcs/small_sample/0/*', dataSpecs), # Class 0
            #get_images('/vol/vssp/mammo2/will/data/simulated/calcs/small_sample/1/*', dataSpecs) # Class 1
            get_images('/user/HS204/wm0015/student/allCalcs/0/*', dataSpecs), # Class 0
            get_images('/user/HS204/wm0015/student/allCalcs/1/*', dataSpecs) # Class 1
    ))  
    # Normalise
    data['img'] = data['img']/255
    
    print('dataSpecs = ', dataSpecs['classLength'])
    labels_bg = get_labels_one_hot(2, 0, dataSpecs['classLength'][0])  
    labels_calc = get_labels_one_hot(2, 1, dataSpecs['classLength'][1])
    data['label'] = np.concatenate((
            get_labels_one_hot(2, 0, dataSpecs['classLength'][0]), # Class 0 
            get_labels_one_hot(2, 1, dataSpecs['classLength'][1]) # Class 1
    ))
    # Drop from 3 colour channels to 1 (greyscale)
    if 1==1:
        data['img'] = data['img'][:,:,:,0]
        data['img'] = np.reshape(data['img'], (data['img'].shape[0],data['img'].shape[1],data['img'].shape[2],1))
        print('new data shape = ', data['img'].shape)
    
    
    
    
    # Shuffle data
    seed = 33
    np.random.seed(seed) # Has to be set before each use of random
    shuffleMask = np.random.permutation(data['img'].shape[0])    
    data['img'] = data['img'][shuffleMask, :, :, :]
    data['label'] = data['label'][shuffleMask, :]
    
    # Split traing and validation data        
    splitRatio = 0.9
    splitPoint = math.floor(data['img'].shape[0]*splitRatio)
    train_data = {'img': data['img'][0:splitPoint], 'label': data['label'][0:splitPoint]}
    validation_data = {'img': data['img'][splitPoint:], 'label': data['label'][splitPoint:]}
    print('train_data[img].shape = ', train_data['img'].shape)
    print('train_data[label].shape = ', train_data['label'].shape)
    print('validation_data[img].shape = ', validation_data['img'].shape)
    print('valdiation_data[label].shape = ', validation_data['label'].shape)
    
    # Print image    
#     img_calc = train_data['img']   
#     plt.imshow(img_calc[0], cmap='gray')
#     plt.show()
    
    # Keras!
    model = Sequential()
    print(train_data['img']) 
    
    # Layer 1
    model.add(Conv2D(32, (3,3), activation='relu', input_shape=(385, 385, 1), data_format='channels_last'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    # Layer 2
    model.add(Conv2D(32, (3,3), activation='relu')) 
    model.add(MaxPooling2D(pool_size=(2, 2)))
    # Layer 3    
    model.add(Conv2D(32, (3,3), activation='relu'))  
    model.add(MaxPooling2D(pool_size=(2, 2)))
    # Layer 4     
    model.add(Conv2D(32, (3,3), activation='relu'))   
    model.add(MaxPooling2D(pool_size=(2, 2)))    
    # Layer 5     
    model.add(Conv2D(32, (3,3), activation='relu'))   
    model.add(MaxPooling2D(pool_size=(2, 2)))
    # Layer 6
    model.add(Flatten())
    model.add(Dense(1024, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(2, activation='softmax'))
    
    print('COMPILE\n')
    sgd = optimizers.SGD(lr=5, decay=1e-6, momentum=0.9, nesterov=True)
    adam = optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False) #0.001
    model.compile(loss='binary_crossentropy',
            optimizer=adam,
            metrics=['accuracy']) # Accuracy will now be returned when evaluate is called
    
    model.summary()   
    print('TRAIN\n')
    # Train
    model.fit(train_data['img'], train_data['label'], 
           batch_size=100, epochs=100, verbose=1)
    
    # Evaluate
    score = model.evaluate(validation_data['img'], validation_data['label'], verbose=0)
    print('The score is......\n', score)
    
if __name__ == "__main__":
    main()

2.2.0
Started
dataSpecs =  [901, 719]
new data shape =  (1620, 385, 385, 1)
train_data[img].shape =  (1458, 385, 385, 1)
train_data[label].shape =  (1458, 2)
validation_data[img].shape =  (162, 385, 385, 1)
valdiation_data[label].shape =  (162, 2)
[[[[0.61960784]
   [0.58039216]
   [0.56862745]
   ...
   [0.34901961]
   [0.3254902 ]
   [0.30980392]]

  [[0.57254902]
   [0.54509804]
   [0.54901961]
   ...
   [0.35294118]
   [0.3254902 ]
   [0.30588235]]

  [[0.50980392]
   [0.49803922]
   [0.51764706]
   ...
   [0.37254902]
   [0.34509804]
   [0.31372549]]

  ...

  [[0.48235294]
   [0.48235294]
   [0.4745098 ]
   ...
   [0.6       ]
   [0.58431373]
   [0.62352941]]

  [[0.45098039]
   [0.44313725]
   [0.43921569]
   ...
   [0.62352941]
   [0.6       ]
   [0.63529412]]

  [[0.44705882]
   [0.43921569]
   [0.43921569]
   ...
   [0.67843137]
   [0.64313725]
   [0.65098039]]]


 [[[0.23921569]
   [0.23921569]
   [0.22352941]
   ...
   [0.57254902]
   [0.59215686]
   [0.58431373]]

  [[0.23

1458/1458 [==============================] - 5s 3ms/step - loss: 0.0128 - acc: 0.9966
Epoch 21/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0080 - acc: 0.9979
Epoch 22/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0029 - acc: 1.0000
Epoch 23/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0019 - acc: 0.9993
Epoch 24/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0032 - acc: 0.9986
Epoch 25/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0020 - acc: 1.0000
Epoch 26/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0028 - acc: 0.9993
Epoch 27/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0108 - acc: 0.9966
Epoch 28/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0045 - acc: 0.9986
Epoch 29/100
1458/1458 [==============================] - 5s 3ms/step - loss: 0.0040 - acc: 0.9973
Epoch 30/100
1458/1458 

1458/1458 [==============================] - 5s 3ms/step - loss: 6.0199e-06 - acc: 1.0000
The score is......
 [0.05417630682090997, 0.9814814814814815]


In [ ]:
print('hello world')